version: '3.9'

services:
  scheduler:
    build:
      context: .
      dockerfile: ./propius/controller/scheduler/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - client_db_0
    - client_db_1
    - job_db
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit

  job_manager:
    build:
      context: .
      dockerfile: ./propius/controller/job_manager/Dockerfile
    ports:
    - 50001:50001
    volumes:
    - ./propius:/propius
    depends_on:
    - scheduler
    - job_db
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit

  load_balancer:
    build:
      context: .
      dockerfile: ./propius/controller/load_balancer/Dockerfile
    ports:
    - 50002:50002
    volumes:
    - ./propius:/propius
    depends_on:
    - client_manager_0
    - client_manager_1
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit

  job_db:
    build:
      context: .
      dockerfile: ./propius/controller/database/Dockerfile
    command: ['6379']
    environment:
    - TZ=America/Detroit

  client_manager_0:
    build:
      context: .
      dockerfile: ./propius/controller/client_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - job_db
    - client_db_0
    - scheduler
    command:
    - '0'
    environment:
    - TZ=America/Detroit
    stop_signal: SIGINT
  client_db_0:
    build:
      context: .
      dockerfile: ./propius/controller/database/Dockerfile
    command:
    - '6380'
    environment:
    - TZ=America/Detroit
  client_manager_1:
    build:
      context: .
      dockerfile: ./propius/controller/client_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - job_db
    - client_db_1
    - scheduler
    command:
    - '1'
    environment:
    - TZ=America/Detroit
    stop_signal: SIGINT
  client_db_1:
    build:
      context: .
      dockerfile: ./propius/controller/database/Dockerfile
    command:
    - '6381'
    environment:
    - TZ=America/Detroit
