version: '3.9'

services:
  scheduler:
    build:
      context: .
      dockerfile: ./propius/controller/scheduler/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - client_db_0
    - client_db_1
    - job_db
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  job_manager:
    build:
      context: .
      dockerfile: ./propius/controller/job_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - scheduler
    - job_db
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  load_balancer:
    build:
      context: .
      dockerfile: ./propius/controller/load_balancer/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - client_manager_0
    - client_manager_1
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  job_db:
    build:
      context: .
      dockerfile: ./propius/controller/database/Dockerfile
    command: ['6379']
    environment:
    - TZ=America/Detroit
  client_manager_0:
    build:
      context: .
      dockerfile: ./propius/controller/client_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - job_db
    - client_db_0
    - scheduler
    command:
    - '0'
    environment:
    - TZ=America/Detroit
    stop_signal: SIGINT
  client_db_0:
    build:
      context: .
      dockerfile: ./propius/controller/database/Dockerfile
    command:
    - '6380'
    environment:
    - TZ=America/Detroit
  client_manager_1:
    build:
      context: .
      dockerfile: ./propius/controller/client_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - job_db
    - client_db_1
    - scheduler
    command:
    - '1'
    environment:
    - TZ=America/Detroit
    stop_signal: SIGINT
  client_db_1:
    build:
      context: .
      dockerfile: ./propius/controller/database/Dockerfile
    command:
    - '6381'
    environment:
    - TZ=America/Detroit
  jobs_0:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '0'
    - '2'
    - '0'
    environment:
    - TZ=America/Detroit
  jobs_1:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '2'
    - '4'
    - '1'
    environment:
    - TZ=America/Detroit
  jobs_2:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '4'
    - '6'
    - '2'
    environment:
    - TZ=America/Detroit
  jobs_3:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '6'
    - '8'
    - '3'
    environment:
    - TZ=America/Detroit
  jobs_4:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '8'
    - '10'
    - '4'
    environment:
    - TZ=America/Detroit
  jobs_5:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '10'
    - '12'
    - '5'
    environment:
    - TZ=America/Detroit
  jobs_6:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '12'
    - '14'
    - '6'
    environment:
    - TZ=America/Detroit
  jobs_7:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '14'
    - '16'
    - '7'
    environment:
    - TZ=America/Detroit
  jobs_8:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '16'
    - '18'
    - '8'
    environment:
    - TZ=America/Detroit
  jobs_9:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '18'
    - '20'
    - '9'
    environment:
    - TZ=America/Detroit
  clients_0:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '0'
  clients_1:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '1'
  clients_2:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '2'
  clients_3:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '3'
  clients_4:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '4'
  clients_5:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '5'
  clients_6:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '6'
  clients_7:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '7'
  clients_8:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '8'
  clients_9:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '9'
  clients_10:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '10'
  clients_11:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '11'
  clients_12:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '12'
  clients_13:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '13'
  clients_14:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '14'
