# Training and testing aggregator setting
demand: 10
total_round: 100
over_selection: 1.1

sched_timeout: 100
exec_timeout: 1000

# Training and testing client setting
engine: pytorch
model: resnet18
dataset: femnist
learning_rate: 0.05
num_loaders: 4
local_steps: 20
loss_decay: 0.2
batch_size: 30

min_learning_rate: 5.e-5
decay_factor: 0.98
decay_round: 10

gradient_policy: fed-avg
# yogi_eta: 3.e-3
# yogi_tau: 1.e-8
# yogi_beta1: 0.9
# yogi_beta2: 0.99

# Client constraints
public_constraint:
    cpu_f: 0
    ram: 0
    fp16_mem: 0
    android_os: 0
private_constraint:
    dataset_size: 100